### ISSUE TITLE
Unopened <a> tag in beans.twig

### ISSUE THREAD

**Issue by flikkr** [rivets/framework2#6]
Line 76 has a closing link tag without an opening one.

https://github.com/rivets/framework2/blob/d4cc9ae5f7a54ba92a355409bd9b3714bf3f6122/twigs/framework/admin/beans.twig#L76

**Comment by rivets** [comment]
I didn't see this issue till today. Now fixed, though commit doesn't seem to have worked from working copy. Will get it done ASAP.
